"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

prev = 1
curr = 1
max = 4000000

def even_fibonacci(max):
    prev = 1
    curr = 1
    while curr < max:
        next = prev + curr

        if curr % 2 == 0:
            yield curr

        prev, curr = curr, next


even_sum = sum(even_fibonacci(max))
print(even_sum)